/*
 * ChooserList.java
 *
 * Created on 26. Juni 2005, 10:55
 */

/*

npImport - Einlesen-Programm für Nachprüfungsplanung
Copyright (c) 2005 Thomas Perl <thp@perli.net>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/


package at.htlpinkafeld.np.frontend;

import java.util.*;
import javax.swing.*;

import at.htlpinkafeld.np.model.*;

/**
 * Ein Dialog, mit dem man aus einer Liste SQLizable-Objekten ein 
 * bestimmtes Objekt auswählen kann, das danach mit einem 
 * entsprechenden Editor bearbeitet werden kann.
 *
 * @author  Thomas Perl <thp@perli.net>
 */
public class ChooserList extends javax.swing.JDialog {
    private Vector<SQLizable> objekte = null; // Vektor mit Objekten, die auszuwählen sind
    private java.awt.Frame hauptfenster = null; // Speichert das Hauptfenster, das wir brauchen
    
    /** Creates new form ChooserList */
    public ChooserList(java.awt.Frame parent, Vector<SQLizable> objekte) {
        super(parent, true);
        
        // Merken von Parametern
        this.objekte = objekte;
        this.hauptfenster = parent;
        
        // Dialog aufbauen
        initComponents();
        
        // Daten in die Liste schreiben
        fillList();
        
        // Fenstergröße anpassen
        pack();
        
        // Minimale Höhe setzen
        FrontendUtil.setMinSize( this, 400, 0);
        
        // Fenster auf Bildschirm zentrieren
        FrontendUtil.centerForm( this);
    }
    
    public void fillList() {
        DefaultListModel dlm = new DefaultListModel();
        
        for( int i=0; i<objekte.size(); i++)
            dlm.addElement( objekte.get(i));
        
        ChooserList.setModel( dlm);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        BodyPanel = new javax.swing.JPanel();
        ListScroller = new javax.swing.JScrollPane();
        ChooserList = new javax.swing.JList();
        BottomPanel = new javax.swing.JPanel();
        BtnBearbeiten = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datensatz ausw\u00e4hlen");
        BodyPanel.setLayout(new java.awt.BorderLayout());

        BodyPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 10, 1, 10)));
        ListScroller.setViewportView(ChooserList);

        BodyPanel.add(ListScroller, java.awt.BorderLayout.CENTER);

        getContentPane().add(BodyPanel, java.awt.BorderLayout.CENTER);

        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BtnBearbeiten.setText("Bearbeiten");
        BtnBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBearbeitenActionPerformed(evt);
            }
        });

        BottomPanel.add(BtnBearbeiten);

        BtnClose.setText("Schlie\u00dfen");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        BottomPanel.add(BtnClose);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Um einen Datensatz zu bearbeiten, bitte den gew\u00fcnschten Datensatz ausw\u00e4hlen:");
        jLabel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void BtnBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBearbeitenActionPerformed
        int sel = ChooserList.getSelectedIndex();
        
        if( sel != -1)
        {
            SQLizable item = objekte.get(sel);
            
            /* Wenn es ein Lehrer ist */
            if( item.getClass().equals( Lehrer.class))
                new LehrerEditor( hauptfenster, (Lehrer)item).setVisible( true);
            
            /* Wenn es ein Gegensatnd ist */
            if( item.getClass().equals( Gegenstand.class))
                new GegenstandEditor( hauptfenster, (Gegenstand)item).setVisible( true);
        }
        
        /**
         * Inhalt der Liste neu zeichnen - da nicht Strings, sondern 
         * die konkreten Elemente drinnen stehen, wird der Inhalt der 
         * Liste automatisch aktualisiert :)
         **/
        ChooserList.repaint();
    }//GEN-LAST:event_BtnBearbeitenActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        // Einfach schließen :)
        dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JButton BtnBearbeiten;
    private javax.swing.JButton BtnClose;
    private javax.swing.JList ChooserList;
    private javax.swing.JScrollPane ListScroller;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
