/*
 * LehrerEditor.java
 *
 * Created on 26. Juni 2005, 10:32
 */

/*

npImport - Einlesen-Programm für Nachprüfungsplanung
Copyright (c) 2005 Thomas Perl <thp@perli.net>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/


package at.htlpinkafeld.np.frontend;

import at.htlpinkafeld.np.model.*;

/**
 * Dies ist ein Dialog, mit dem ein Objekt vom Typ Lehrer 
 * editiert werden kann.
 *
 * @author  Thomas Perl <thp@perli.net>
 */
public class LehrerEditor extends javax.swing.JDialog {
    private Lehrer lehrer = null; // Lehrer, der zu editieren ist
    
    /**
     * Erstellt einen neuen Lehrer-Editor Dialog.
     *
     * @param parent Elternfenster dieses Dialogs
     * @param lehrer Lehrer, der zu editieren ist
     **/
    public LehrerEditor(java.awt.Frame parent, Lehrer lehrer) {
        super(parent, true);
        
        this.lehrer = lehrer;
        
        // Dialog aufbauen
        initComponents();
        
        // Dialog mit Werten füllen
        fillValues();
        
        // Dialog in der Bildschirmmitte anzeigen
        FrontendUtil.centerForm( this);
    }
    
    /**
     * Füllt die Felder dieses Dialogs mit Werten aus dem Lehrer-Objekt.
     **/
    private void fillValues() {
        VarUid.setText( Integer.toString( lehrer.getUid()));
        VarName.setText( lehrer.getName());
        VarTag1.setSelected( lehrer.isTag1());
        VarTag2.setSelected( lehrer.isTag2());
    }
    
    /**
     * Speichert die Eingabedaten vom Dialog in das mit dem Dialog 
     * verknüpfte Lehrer-Objekt.
     **/
    private void saveValues() {
        lehrer.setName( VarName.getText());
        lehrer.setTag1( VarTag1.isSelected());
        lehrer.setTag2( VarTag2.isSelected());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ButtonPanel = new javax.swing.JPanel();
        BtnSpeichern = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        LblUid = new javax.swing.JLabel();
        VarUid = new javax.swing.JLabel();
        LblName = new javax.swing.JLabel();
        VarName = new javax.swing.JTextField();
        LblVerf = new javax.swing.JLabel();
        VarTag1 = new javax.swing.JCheckBox();
        LblVerf2 = new javax.swing.JLabel();
        VarTag2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lehrer-Editor");
        ButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BtnSpeichern.setText("Speichern");
        BtnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSpeichernActionPerformed(evt);
            }
        });

        ButtonPanel.add(BtnSpeichern);

        BtnCancel.setText("Abbrechen");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        ButtonPanel.add(BtnCancel);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.SOUTH);

        MainPanel.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        MainPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        LblUid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblUid.setText("UID:");
        MainPanel.add(LblUid);

        VarUid.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        VarUid.setText("001");
        MainPanel.add(VarUid);

        LblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblName.setText("Name bzw K\u00fcrzel des Lehrers:");
        MainPanel.add(LblName);

        VarName.setText("ABCD");
        MainPanel.add(VarName);

        LblVerf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblVerf.setText("Verf\u00fcgbarkeit an folgenden Tagen:");
        MainPanel.add(LblVerf);

        VarTag1.setSelected(true);
        VarTag1.setText("am 1. Tag");
        MainPanel.add(VarTag1);

        LblVerf2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MainPanel.add(LblVerf2);

        VarTag2.setSelected(true);
        VarTag2.setText("am 2. Tag");
        MainPanel.add(VarTag2);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        // Abbrechen geklickt - nur beenden
        dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSpeichernActionPerformed
        // Daten vom Dialog in das Objekt speichern
        saveValues();
        
        // Dialog beenden
        dispose();
    }//GEN-LAST:event_BtnSpeichernActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnSpeichern;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblUid;
    private javax.swing.JLabel LblVerf;
    private javax.swing.JLabel LblVerf2;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField VarName;
    private javax.swing.JCheckBox VarTag1;
    private javax.swing.JCheckBox VarTag2;
    private javax.swing.JLabel VarUid;
    // End of variables declaration//GEN-END:variables
    
}
