/*
 * TableShowDialog.java
 *
 * Created on 10. März 2005, 17:35
 */

package at.htlpinkafeld.np.frontend;

import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author  Thomas Perl <thp@perli.net>
 */
public class TableShowDialog extends javax.swing.JDialog {
    
    /**
     * Erstellt einen neuen Dialog, der eine JTable mit 
     * den Daten, die sich in headers und data befinden.
     *
     * @param headers Die Überschriften der Spalten, oder null
     * @param data Die Spalten und Zeilen der Tabelle
     */
    public TableShowDialog( String title, Vector headers, Vector data) {
        super( new JFrame(), false);
        initComponents();
        
        setTitle( title);
        Tabelle.setModel( new DefaultTableModel( data, headers));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ScrollPane = new javax.swing.JScrollPane();
        Tabelle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Tabelle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScrollPane.setViewportView(Tabelle);

        getContentPane().add(ScrollPane, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-440)/2, (screenSize.height-353)/2, 440, 353);
    }//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit( 0);
    }//GEN-LAST:event_formWindowClosed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable Tabelle;
    // End of variables declaration//GEN-END:variables
    
}
