/*
 * GegenstandEditor.java
 *
 * Created on 26. Juni 2005, 11:42
 */

/*

npImport - Einlesen-Programm für Nachprüfungsplanung
Copyright (c) 2005 Thomas Perl <thp@perli.net>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/

package at.htlpinkafeld.np.frontend;

import at.htlpinkafeld.np.model.*;

/**
 * Dieser Editor kann einen Gegenstand bearbeiten.
 *
 * @author  Thomas Perl <thp@perli.net>
 */
public class GegenstandEditor extends javax.swing.JDialog {
    private Gegenstand gegenstand = null; // Das mit diesem Dialog verknüpfte Objekt
    
    /**
     * Erstellt einen neuen GegenstandEditor.
     *
     * @param parent Elternfenster
     * @param gegenstand Der zu editierende Gegenstand
     **/
    public GegenstandEditor(java.awt.Frame parent, Gegenstand gegenstand) {
        super(parent, true);
        
        // Gegenstand-Objekt lokal speichern
        this.gegenstand = gegenstand;
        
        // Komponenten auf dem Dialog erstellen
        initComponents();
        
        // Werte eintragen in den Dialog
        fillValues();
        
        // Fenster auf Bildschirm zentrieren
        FrontendUtil.centerForm( this);
    }

    
    /**
     * Füllt die Felder dieses Dialogs mit Werten aus dem Gegenstand-Objekt.
     **/
    private void fillValues() {
        VarUid.setText( Integer.toString( gegenstand.getUid()));
        VarName.setText( gegenstand.getName());
        VarMuendlich.setSelected( gegenstand.isMuendlich());
        VarSchriftlich.setSelected( gegenstand.isSchriftlich());
        VarGruppe.setText( Integer.toString( gegenstand.getGruppe()));
    }
    
    /**
     * Speichert die Eingabedaten vom Dialog in das mit dem Dialog 
     * verknüpfte Gegenstand-Objekt.
     **/
    private void saveValues() {
        gegenstand.setName( VarName.getText());
        gegenstand.setMuendlich( VarMuendlich.isSelected());
        gegenstand.setSchriftlich( VarSchriftlich.isSelected());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        MainPanel = new javax.swing.JPanel();
        LblUid = new javax.swing.JLabel();
        VarUid = new javax.swing.JLabel();
        LblName = new javax.swing.JLabel();
        VarName = new javax.swing.JTextField();
        LblArt = new javax.swing.JLabel();
        VarMuendlich = new javax.swing.JCheckBox();
        LblArt2 = new javax.swing.JLabel();
        VarSchriftlich = new javax.swing.JCheckBox();
        LblGruppe = new javax.swing.JLabel();
        VarGruppe = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        BtnSpeichern = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gegenstand bearbeiten");
        MainPanel.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        MainPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        LblUid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblUid.setText("UID:");
        MainPanel.add(LblUid);

        VarUid.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        VarUid.setText("001");
        MainPanel.add(VarUid);

        LblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblName.setText("Bezeichnung des Gegenstands:");
        MainPanel.add(LblName);

        VarName.setText("PREU");
        MainPanel.add(VarName);

        LblArt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblArt.setText("Art der Wiederholungspr\u00fcfung:");
        MainPanel.add(LblArt);

        VarMuendlich.setSelected(true);
        VarMuendlich.setText("m\u00fcndlich");
        MainPanel.add(VarMuendlich);

        LblArt2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MainPanel.add(LblArt2);

        VarSchriftlich.setText("schriftlich");
        MainPanel.add(VarSchriftlich);

        LblGruppe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblGruppe.setText("Gruppen-ID:");
        MainPanel.add(LblGruppe);

        VarGruppe.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        VarGruppe.setText("1");
        MainPanel.add(VarGruppe);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        ButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BtnSpeichern.setText("Speichern");
        BtnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSpeichernActionPerformed(evt);
            }
        });

        ButtonPanel.add(BtnSpeichern);

        BtnCancel.setText("Abbrechen");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        ButtonPanel.add(BtnCancel);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void BtnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSpeichernActionPerformed
        // Daten in den Gegenstand zurückspeichern
        saveValues();
        
        // Dialog schließen
        dispose();
    }//GEN-LAST:event_BtnSpeichernActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        // Nicht speichern - einfach beenden
        dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnSpeichern;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JLabel LblArt;
    private javax.swing.JLabel LblArt2;
    private javax.swing.JLabel LblGruppe;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblUid;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel VarGruppe;
    private javax.swing.JCheckBox VarMuendlich;
    private javax.swing.JTextField VarName;
    private javax.swing.JCheckBox VarSchriftlich;
    private javax.swing.JLabel VarUid;
    // End of variables declaration//GEN-END:variables
    
}
